### ISSUE TITLE
Package quanteda.corpora?

### ISSUE THREAD

**Issue by vallivh** [Knowerbescheidt/Text-Ming-Dashboard#2]
<img width="611" alt="Bildschirmfoto 2019-08-14 um 17 11 42" src="https://user-images.githubusercontent.com/53994707/63032693-9be03c00-beb6-11e9-8cbb-eb94264dde99.png">

Irgendwie taucht dieser Fehler auf, wenn ich Shiny laufen lasse. Wird "quanteda.corpora" irgendwo aufgerufen?

**Comment by vallivh** [comment]
Ah verstanden! Das ist einfach kein Standard-R-Package. Kann man das dann mit ins Repo packen, dass es sofort zur Verfügung steht? Oder in den Code?

**Comment by vallivh** [comment]
Der Installationsbefehl steht jetzt in tm.R, halb elegant aber funktioniert.

**Comment by Knowerbescheidt** [comment]
Ich glaube das ist gar nicht nötig das war nur ein altes Package, was ich für einen ersten Test genutzt habe. Kann also raus bei mir funktioniert alles auch wenn ich es auskommentiere.
Wenn das bei dir dann auch funktioniert kannst du diesen Issue schließen.
