### ISSUE TITLE
App_dashboard muss in die oberste Ebene, 

### ISSUE THREAD

**Issue by vallivh** [Knowerbescheidt/Text-Ming-Dashboard#3]
nicht im "Shiny"-Ordner, sonst funktioniert getwd() nicht, wenn die App läuft. Durch "Run App" wird sonst immer noch "/Shiny/" an den Pfad des Working Directories gehängt. 

Vorher wird er aber korrekt ohne ausgegeben (bei mir als "/Users/Valentin/Documents/DA/Text-Ming-Dashboard"). 

Liegt wahrscheinlich am Shiny Setup...

**Comment by Knowerbescheidt** [comment]
Ich würde die Ordner-Struktur eigentlich ganz gern beibehalten, da ich finde sie trägt massiv zur Übersichtlichkeit bei.
Da ich nicht genau dein Problem verstehe würde ich auch das auf morgen verschieben.
zur Not müssen wir die Ordner-Struktur anpassen, aber das sehen wir dann morgen

**Comment by vallivh** [comment]
Ich zeige dir das Problem morgen. Eigentlich ist das einzige, was ich verschieben musste, die Shiny App Datei, in der die App tatsächlich gestartet wird (also App_Dashboard.R). Alles andere funktioniert wunderbar, wie es ist, und das würde ich auch beibehalten.
