### ISSUE TITLE
Objekt 'Token_data' nicht gefunden

### ISSUE THREAD

**Issue by vallivh** [Knowerbescheidt/Text-Ming-Dashboard#5]
Der Fehler tritt sowohl bei Collocations als auch bei der Sentiment Analysis auf. Wird eventuell der Datensatz nicht richtig eingelesen?

**Comment by Knowerbescheidt** [comment]
Der Fehler tritt bei mir nicht auf besprechen wir morgen.

**Comment by Knowerbescheidt** [comment]
Gelöst
