### ISSUE TITLE
Woher genau kommt dfm_data und wann ist es eine Funktion/Variable?

### ISSUE THREAD

**Issue by vallivh** [Knowerbescheidt/Text-Ming-Dashboard#6]
`dfm_data <- eventReactive(input$select_data, {
    data_prep_dfm(
      paste0(getwd(),
        "/Daten/Amazon_data/",
        input$Data_set
      )
    )
  })
  observeEvent(input$select_data, {
    #assign dfm_data zu dfm_data
    assign(x = "dfm_data",
           value = dfm_data,
           envir = globalenv())
  })`

Was wird hier was zugewiesen? Die globale Variable der Funktion?

**Comment by Knowerbescheidt** [comment]
Hey,
also so wie ich es verstanden habe ist ein reaktiver Value immer dennoch ein Wert.
Wenn er aber als reaktiver wert aufgerufen wird, so wird er statt dfm_data zu dfm_data() daher vermutlich deine Frage ob er zur Funktion wird. Meine Antwort Nein er wird zu einem reaktiven Value, der danach in allen Funktionen mit dfm_data() als reaktiver value aufgerufen werden muss. (Es kann sein, dass ich dies in einigen Modulen noch nicht angepasst habe, und noch auf einen vorher festgelegten nicht reaktiven Wert dfm_data verweise.

Ich assigne danach diesen reaktiven Wert in die global environment damit andere Module ohne Probleme darauf zugreifen können. 
Das ist jedoch eine Ausnahme, da man eigentlich die Module getrennt einsetzen will dies ist allerdings eine notwendige Verknüpfung...
Hoffe das hilft.
